"""Cambiar is_read a status en messages

Revision ID: 74301c042cec
Revises: b780a44f5b37
Create Date: 2025-10-31 16:34:00.067837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74301c042cec'
down_revision: Union[str, Sequence[str], None] = 'b780a44f5b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.String(length=250), nullable=True))
    op.drop_column('messages', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
