version: "3.9"

services:

  # Backend
  backend:
    build:
      context: ../../apps/backend
      dockerfile: ../../infra/docker/backend.Dockerfile
    container_name: portfolio_backend
    ports:
      - "8000:8000"
    env_file:
      - ../../apps/backend/.env
    depends_on:
      - db
    volumes:
      - ../../apps/backend:/app

  # Frontend
  frontend: 
    build:
      context: ../../apps/frontend
      dockerfile: ../../infra/docker/web.Dockerfile
    container_name: portfolio_frontend
    ports:
      - "3000:3000"
    volumes:
      - ../../apps/frontend:/app
      - node_modules:/app/node_modules

  # PostgreSQL
  db:
    image: postgres:15
    container_name: portfolio_db
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
      POSTGRES_DB: portfolio_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # # Nginx
  # nginx:
  #   image: nginx:1.26
  #   container_name: portfolio_nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./infra/nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - frontend
  #     - backend

  redis: 
    image: redis:7.2
    container_name: portfolio_redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data


volumes:
  db_data:
    name: db_data
  node_modules:
    name: node_modules
  redis_data:
    name: redis_data